name = "mr4689373-higher-siegel-weil-formula-for-unitary-groups-the-non-singular-terms"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MR4689373HigherSiegelWeilFormulaForUnitaryGroupsTheNonSingularTerms"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "MR4689373HigherSiegelWeilFormulaForUnitaryGroupsTheNonSingularTerms"
