import AlgebraicJacobian.Picard.RelativeSpec
import AlgebraicJacobian.Picard.QuotScheme
import AlgebraicJacobian.Picard.GradedHilbertSerre
import AlgebraicJacobian.Picard.GrassmannianCells
import AlgebraicJacobian.Picard.GlueDescent
import AlgebraicJacobian.Picard.GrassmannianQuot
import AlgebraicJacobian.Picard.SectionGradedRing
